### ISSUE TITLE
./node_modules/.bin/av init error

### ISSUE THREAD

**Issue by availityJchristofoli** [Availity/availity-toolkit#29]
Followed the [Getting Started](https://github.com/Availity/availity-toolkit#getting-started) steps in the readme to create a new project. At the './node_modules/.bin/av init' step I ran into this error. Tried with node 5.3.0 and 6.3.1

> ./node_modules/.bin/av init
> ? author name: 
> ? author email: 
> ? project name: dashboard
> ? project description: Dashboard
> ? project version: 0.0.1
> ? git url: 
> ? license UNLICENSED
> ? keywords - separated by commas: () 

/Users/foo/workspaces/barProject/node_modules/rx/dist/rx.js:77
    throw e;
    ^

TypeError: value.toLowerCase is not a function
    at Object.validate (/Users/foo/workspaces/barProject/node_modules/availity-workflow/cli/commands/init.js:118:33)
    at /Users/foo/workspaces/barProject/node_modules/inquirer/node_modules/run-async/index.js:26:25
    at /Users/foo/workspaces/barProject/node_modules/inquirer/node_modules/run-async/index.js:25:19
    at /Users/foo/workspaces/barProject/node_modules/inquirer/lib/prompts/base.js:89:14
    at process._tickCallback (internal/process/next_tick.js:103:7)

> foo$ 
> foo$ node -v
> v6.3.1

**Comment by availityJchristofoli** [comment]
Looks like this is an issue with availity-workflow treating an array of strings as a string. Closing this and making an issue in the other repo.
